"""TAC Bootstrap Domain Models"""

from tac_bootstrap.domain.entity_config import EntitySpec, FieldSpec, FieldType
from tac_bootstrap.domain.models import (
    AgenticProvider,
    AgenticSpec,
    Architecture,
    BootstrapConfig,
    ClaudeCommandsConfig,
    ClaudeConfig,
    ClaudeSettings,
    CommandsSpec,
    DefaultWorkflow,
    Framework,
    Language,
    LoggingConfig,
    ModelPolicy,
    PackageManager,
    PathsSpec,
    ProjectMode,
    ProjectSpec,
    RunIdStrategy,
    SafetyConfig,
    TACConfig,
    TemplatesConfig,
    WorkflowsConfig,
    WorktreeConfig,
    get_default_commands,
    get_frameworks_for_language,
    get_package_managers_for_language,
)
from tac_bootstrap.domain.migrations import (
    MIGRATION_REGISTRY,
    Migration,
    get_latest_version,
    get_migration_path,
    migrate_v1_to_v2,
    migrate_v2_to_v1,
)
from tac_bootstrap.domain.validators import (
    ARCHITECTURES_REQUIRING_BASE_CLASSES,
    COMPATIBLE_FRAMEWORKS,
    COMPATIBLE_PACKAGE_MANAGERS,
    ValidationIssue,
    validate_architecture_framework,
    validate_framework_language,
    validate_package_manager_language,
)

__all__ = [
    # Entity configuration models
    "EntitySpec",
    "FieldSpec",
    "FieldType",
    # Configuration models
    "TACConfig",
    "ProjectSpec",
    "PathsSpec",
    "CommandsSpec",
    "AgenticSpec",
    "ClaudeConfig",
    "ClaudeSettings",
    "ClaudeCommandsConfig",
    "TemplatesConfig",
    "BootstrapConfig",
    "WorktreeConfig",
    "LoggingConfig",
    "SafetyConfig",
    "WorkflowsConfig",
    "ModelPolicy",
    # Enums
    "Language",
    "Framework",
    "Architecture",
    "PackageManager",
    "ProjectMode",
    "AgenticProvider",
    "RunIdStrategy",
    "DefaultWorkflow",
    # Helper functions
    "get_frameworks_for_language",
    "get_package_managers_for_language",
    "get_default_commands",
    # Validators
    "ValidationIssue",
    "validate_framework_language",
    "validate_package_manager_language",
    "validate_architecture_framework",
    "COMPATIBLE_FRAMEWORKS",
    "COMPATIBLE_PACKAGE_MANAGERS",
    "ARCHITECTURES_REQUIRING_BASE_CLASSES",
    # Migrations
    "Migration",
    "MIGRATION_REGISTRY",
    "get_latest_version",
    "get_migration_path",
    "migrate_v1_to_v2",
    "migrate_v2_to_v1",
]
