"""TAC Bootstrap Domain Models"""

from tac_bootstrap.domain.entity_config import EntitySpec, FieldSpec, FieldType
from tac_bootstrap.domain.models import (
    AgenticProvider,
    AgenticSpec,
    Architecture,
    BootstrapConfig,
    ClaudeCommandsConfig,
    ClaudeConfig,
    ClaudeSettings,
    CommandsSpec,
    DefaultWorkflow,
    Framework,
    Language,
    LoggingConfig,
    ModelPolicy,
    PackageManager,
    PathsSpec,
    ProjectMode,
    ProjectSpec,
    RunIdStrategy,
    SafetyConfig,
    TACConfig,
    TemplatesConfig,
    WorkflowsConfig,
    WorktreeConfig,
    get_default_commands,
    get_frameworks_for_language,
    get_package_managers_for_language,
)

__all__ = [
    # Entity configuration models
    "EntitySpec",
    "FieldSpec",
    "FieldType",
    # Configuration models
    "TACConfig",
    "ProjectSpec",
    "PathsSpec",
    "CommandsSpec",
    "AgenticSpec",
    "ClaudeConfig",
    "ClaudeSettings",
    "ClaudeCommandsConfig",
    "TemplatesConfig",
    "BootstrapConfig",
    "WorktreeConfig",
    "LoggingConfig",
    "SafetyConfig",
    "WorkflowsConfig",
    "ModelPolicy",
    # Enums
    "Language",
    "Framework",
    "Architecture",
    "PackageManager",
    "ProjectMode",
    "AgenticProvider",
    "RunIdStrategy",
    "DefaultWorkflow",
    # Helper functions
    "get_frameworks_for_language",
    "get_package_managers_for_language",
    "get_default_commands",
]
