#!/usr/bin/env bash
# Documentation Generators Orchestration Script
# Auto-generated by TAC Bootstrap
#
# This script orchestrates the execution of documentation generators in sequence:
# 1. gen_docstring_jsdocs.py - Enriches inline documentation
# 2. gen_docs_fractal.py - Generates folder-level fractal documentation

set -euo pipefail

# ============================================================================
# Configuration
# ============================================================================
REPO_ROOT="tac_bootstrap_cli"
SCRIPTS_DIR="$(dirname "$0")"
DOCS_DIR="docs"

# ============================================================================
# Helper Functions
# ============================================================================
show_help() {
    cat << EOF
Usage: run_generators.sh [OPTIONS]

Orchestrates documentation generators in the correct sequence.

Options:
  --dry-run       Show what would be done without making changes
  --changed-only  Only process files changed since last commit (docstrings only)
  --help          Show this help message

Examples:
  # Preview changes without modifying files
  ./run_generators.sh --dry-run

  # Update only changed files' docstrings, then regenerate all fractal docs
  ./run_generators.sh --changed-only

  # Combine flags
  ./run_generators.sh --dry-run --changed-only
EOF
}

# ============================================================================
# Preflight Checks
# ============================================================================

# Check required commands
command -v python3 >/dev/null 2>&1 || {
    echo "Error: python3 is required but not installed." >&2
    exit 1
}

command -v uv >/dev/null 2>&1 || {
    echo "Error: uv is required but not installed." >&2
    echo "Install with: curl -LsSf https://astral.sh/uv/install.sh | sh" >&2
    exit 1
}

# Check generator scripts exist
[ -f "$SCRIPTS_DIR/gen_docstring_jsdocs.py" ] || {
    echo "Error: gen_docstring_jsdocs.py not found in $SCRIPTS_DIR" >&2
    exit 1
}

[ -f "$SCRIPTS_DIR/gen_docs_fractal.py" ] || {
    echo "Error: gen_docs_fractal.py not found in $SCRIPTS_DIR" >&2
    exit 1
}

# Check REPO_ROOT exists
[ -d "$REPO_ROOT" ] || {
    echo "Error: REPO_ROOT directory not found: $REPO_ROOT" >&2
    exit 1
}

# Create DOCS_DIR if missing
mkdir -p "$DOCS_DIR"

# ============================================================================
# Parse Command Line Arguments
# ============================================================================
DRY_RUN=""
CHANGED_ONLY=""

for arg in "$@"; do
    case $arg in
        --help)
            show_help
            exit 0
            ;;
        --dry-run)
            DRY_RUN="--dry-run"
            ;;
        --changed-only)
            CHANGED_ONLY="--changed-only"
            ;;
        *)
            echo "Warning: Unknown option: $arg" >&2
            ;;
    esac
done

# ============================================================================
# Step 1: Enrich Docstrings
# ============================================================================
echo "=== Step 1: Enriching docstrings ==="
uv run "$SCRIPTS_DIR/gen_docstring_jsdocs.py" \
    --repo "$REPO_ROOT" \
    --mode complement \
    $CHANGED_ONLY $DRY_RUN

# ============================================================================
# Step 2: Generate Fractal Documentation
# ============================================================================
echo "=== Step 2: Generating fractal documentation ==="
uv run "$SCRIPTS_DIR/gen_docs_fractal.py" \
    --repo . \
    --docs-root "$DOCS_DIR" \
    --include-root "$REPO_ROOT" \
    --mode complement \
    $DRY_RUN

# ============================================================================
# Done
# ============================================================================
echo "=== Done ==="
